spring:
  application:
    name: FraudDetection

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud_detection
    username: fraud_user
    password: fraud_password
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

# Logging Configuration
logging:
  level:
    com.FraudDetection: DEBUG